added BeeGFS 7.0-rc2

diff --git a/beeond/scripts/lib/beegfs-ondemand-stoplocal b/beeond/scripts/lib/beegfs-ondemand-stoplocal
--- a/beeond/scripts/lib/beegfs-ondemand-stoplocal
+++ b/beeond/scripts/lib/beegfs-ondemand-stoplocal
@@ -91,6 +91,10 @@ sl_unmount_local_mounts()
       fi
    done < "${STATUSFILE}"
    unset IFS
+
+   # try to remove the client module - this is allowed to fail, because we might have a "normal"
+   # beegfs mount somewhere in the system.
+   rmmod beegfs 2>/dev/null || true
 }
 
 # sends a SIGTERM to a process, then waits until the process is stopped or appriximately 10 seconds
